# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20170511_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
